app: # метаданные приложения
    name: 'chat' # наименование приложения
httpd:
    port: "8000" # http порт, который будет пытаться открыть приложения и принимать на него http запросы
    host: ""  # ip адрес хоста который будет занимать приложение, можно оставить пустым
env: production # тип окружения в котором запускается сервис, production - логи в сокращенном формате
log:
    level: debug # уровень логирования сервиса: debug, info, warn, error
    file: "" # имя файла лога, если пусто или stdout - будет выводить в stdout, если указано имя фацйла, будет писать в него

    